version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - express-api
      - whoami

  express-api:
    build:
      context: ./server
    container_name: express-api

  whoami:
    image: traefik/whoami
    container_name: whoami
